[package]
name = "EnyxComposer"
version = "0.1.0"
edition = "2024"

[dependencies]
lambda_runtime = "0.13.0"
serde_json = "1.0.140"
tokio = { version = "1.45.0", features = ["full"] } # for our async runtime
